// Code generated by MockGen. DO NOT EDIT.
// Source: dataref.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/xairline/x-gpt/models"
)

// MockDatarefService is a mock of DatarefService interface.
type MockDatarefService struct {
	ctrl     *gomock.Controller
	recorder *MockDatarefServiceMockRecorder
}

// MockDatarefServiceMockRecorder is the mock recorder for MockDatarefService.
type MockDatarefServiceMockRecorder struct {
	mock *MockDatarefService
}

// NewMockDatarefService creates a new mock instance.
func NewMockDatarefService(ctrl *gomock.Controller) *MockDatarefService {
	mock := &MockDatarefService{ctrl: ctrl}
	mock.recorder = &MockDatarefServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatarefService) EXPECT() *MockDatarefServiceMockRecorder {
	return m.recorder
}

// GetValueByDatarefName mocks base method.
func (m *MockDatarefService) GetValueByDatarefName(clientId, dataref, name string, precision *int8, isByteArray bool) models.DatarefValue {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueByDatarefName", clientId, dataref, name, precision, isByteArray)
	ret0, _ := ret[0].(models.DatarefValue)
	return ret0
}

// GetValueByDatarefName indicates an expected call of GetValueByDatarefName.
func (mr *MockDatarefServiceMockRecorder) GetValueByDatarefName(clientId, dataref, name, precision, isByteArray interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueByDatarefName", reflect.TypeOf((*MockDatarefService)(nil).GetValueByDatarefName), clientId, dataref, name, precision, isByteArray)
}

// SetValueByDatarefName mocks base method.
func (m *MockDatarefService) SetValueByDatarefName(clientId, dataref string, value interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetValueByDatarefName", clientId, dataref, value)
}

// SetValueByDatarefName indicates an expected call of SetValueByDatarefName.
func (mr *MockDatarefServiceMockRecorder) SetValueByDatarefName(clientId, dataref, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValueByDatarefName", reflect.TypeOf((*MockDatarefService)(nil).SetValueByDatarefName), clientId, dataref, value)
}
