// Code generated by MockGen. DO NOT EDIT.
// Source: flight-logs.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockFlightLogsService is a mock of FlightLogsService interface.
type MockFlightLogsService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightLogsServiceMockRecorder
}

// MockFlightLogsServiceMockRecorder is the mock recorder for MockFlightLogsService.
type MockFlightLogsServiceMockRecorder struct {
	mock *MockFlightLogsService
}

// NewMockFlightLogsService creates a new mock instance.
func NewMockFlightLogsService(ctrl *gomock.Controller) *MockFlightLogsService {
	mock := &MockFlightLogsService{ctrl: ctrl}
	mock.recorder = &MockFlightLogsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightLogsService) EXPECT() *MockFlightLogsServiceMockRecorder {
	return m.recorder
}
