// Code generated by MockGen. DO NOT EDIT.
// Source: flight-logs.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	models "github.com/xairline/x-gpt/models"
)

// MockFlightLogsService is a mock of FlightLogsService interface.
type MockFlightLogsService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightLogsServiceMockRecorder
}

// MockFlightLogsServiceMockRecorder is the mock recorder for MockFlightLogsService.
type MockFlightLogsServiceMockRecorder struct {
	mock *MockFlightLogsService
}

// NewMockFlightLogsService creates a new mock instance.
func NewMockFlightLogsService(ctrl *gomock.Controller) *MockFlightLogsService {
	mock := &MockFlightLogsService{ctrl: ctrl}
	mock.recorder = &MockFlightLogsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightLogsService) EXPECT() *MockFlightLogsServiceMockRecorder {
	return m.recorder
}

// GetFlightLogs mocks base method.
func (m *MockFlightLogsService) GetFlightLogs(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetFlightLogs", c)
}

// GetFlightLogs indicates an expected call of GetFlightLogs.
func (mr *MockFlightLogsServiceMockRecorder) GetFlightLogs(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightLogs", reflect.TypeOf((*MockFlightLogsService)(nil).GetFlightLogs), c)
}

// GetLastSyncedLocalIdByUsername mocks base method.
func (m *MockFlightLogsService) GetLastSyncedLocalIdByUsername(username string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastSyncedLocalIdByUsername", username)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastSyncedLocalIdByUsername indicates an expected call of GetLastSyncedLocalIdByUsername.
func (mr *MockFlightLogsServiceMockRecorder) GetLastSyncedLocalIdByUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastSyncedLocalIdByUsername", reflect.TypeOf((*MockFlightLogsService)(nil).GetLastSyncedLocalIdByUsername), username)
}

// SaveFlightStatuses mocks base method.
func (m *MockFlightLogsService) SaveFlightStatuses(statuses []models.FlightStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveFlightStatuses", statuses)
}

// SaveFlightStatuses indicates an expected call of SaveFlightStatuses.
func (mr *MockFlightLogsServiceMockRecorder) SaveFlightStatuses(statuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFlightStatuses", reflect.TypeOf((*MockFlightLogsService)(nil).SaveFlightStatuses), statuses)
}
