// Code generated by MockGen. DO NOT EDIT.
// Source: webSocket.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockWebSocketService is a mock of WebSocketService interface.
type MockWebSocketService struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketServiceMockRecorder
}

// MockWebSocketServiceMockRecorder is the mock recorder for MockWebSocketService.
type MockWebSocketServiceMockRecorder struct {
	mock *MockWebSocketService
}

// NewMockWebSocketService creates a new mock instance.
func NewMockWebSocketService(ctrl *gomock.Controller) *MockWebSocketService {
	mock := &MockWebSocketService{ctrl: ctrl}
	mock.recorder = &MockWebSocketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketService) EXPECT() *MockWebSocketServiceMockRecorder {
	return m.recorder
}

// Upgrade mocks base method.
func (m *MockWebSocketService) Upgrade(c *gin.Context, clientId string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Upgrade", c, clientId)
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockWebSocketServiceMockRecorder) Upgrade(c, clientId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockWebSocketService)(nil).Upgrade), c, clientId)
}
