// Code generated by MockGen. DO NOT EDIT.
// Source: webSocket.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockWebSocketService is a mock of WebSocketService interface.
type MockWebSocketService struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketServiceMockRecorder
}

// MockWebSocketServiceMockRecorder is the mock recorder for MockWebSocketService.
type MockWebSocketServiceMockRecorder struct {
	mock *MockWebSocketService
}

// NewMockWebSocketService creates a new mock instance.
func NewMockWebSocketService(ctrl *gomock.Controller) *MockWebSocketService {
	mock := &MockWebSocketService{ctrl: ctrl}
	mock.recorder = &MockWebSocketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketService) EXPECT() *MockWebSocketServiceMockRecorder {
	return m.recorder
}

// IsClientExist mocks base method.
func (m *MockWebSocketService) IsClientExist(clientId string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsClientExist", clientId)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsClientExist indicates an expected call of IsClientExist.
func (mr *MockWebSocketServiceMockRecorder) IsClientExist(clientId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsClientExist", reflect.TypeOf((*MockWebSocketService)(nil).IsClientExist), clientId)
}

// SendWsMsgByClientId mocks base method.
func (m *MockWebSocketService) SendWsMsgByClientId(clientId, message string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWsMsgByClientId", clientId, message)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendWsMsgByClientId indicates an expected call of SendWsMsgByClientId.
func (mr *MockWebSocketServiceMockRecorder) SendWsMsgByClientId(clientId, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWsMsgByClientId", reflect.TypeOf((*MockWebSocketService)(nil).SendWsMsgByClientId), clientId, message)
}

// Upgrade mocks base method.
func (m *MockWebSocketService) Upgrade(c *gin.Context, clientId string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Upgrade", c, clientId)
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockWebSocketServiceMockRecorder) Upgrade(c, clientId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockWebSocketService)(nil).Upgrade), c, clientId)
}
